"""Add rating column to ServiceRemark

Revision ID: 6fe137cd2c83
Revises: 59def1dfa5bc
Create Date: 2024-11-29 19:11:34.601802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fe137cd2c83'
down_revision = '59def1dfa5bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_remark', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=False, server_default='0.0'))  # Add default value

    # Remove the default value after the column is added
    op.alter_column('service_remark', 'rating', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_remark', schema=None) as batch_op:
        batch_op.drop_column('rating')
    # ### end Alembic commands ###
