"""Initial migration.

Revision ID: 9354b2ad4652
Revises: 
Create Date: 2024-11-29 08:59:08.578056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9354b2ad4652'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=150), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('zip', sa.String(length=20), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=False, server_default=''))

    # Remove the server_default after the columns are added
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('name', server_default=None)
        batch_op.alter_column('phone', server_default=None)
        batch_op.alter_column('address', server_default=None)
        batch_op.alter_column('city', server_default=None)
        batch_op.alter_column('state', server_default=None)
        batch_op.alter_column('zip', server_default=None)
        batch_op.alter_column('country', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('country')
        batch_op.drop_column('zip')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('address')
        batch_op.drop_column('phone')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
